# Generated by Django 4.1.6 on 2023-02-08 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("page", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_by_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_post",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_posts",
                to="page.page",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reply_to_post",
                to="page.post",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="follow_requests",
            field=models.ManyToManyField(
                blank=True,
                related_name="follow_requests_pages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="follower_pages", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_page",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="tags",
            field=models.ManyToManyField(related_name="tag_pages", to="page.tag"),
        ),
    ]
