# Generated by Django 4.1.6 on 2023-02-09 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("page", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="pages", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="tags",
            field=models.ManyToManyField(related_name="pages", to="page.tag"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
